# Generated by Django 5.1.2 on 2024-10-28 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.PositiveIntegerField(default=1000)),
                ('height', models.PositiveIntegerField(default=1000)),
                ('map_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('health', models.PositiveIntegerField(default=100)),
                ('damage', models.PositiveIntegerField(default=10)),
                ('speed', models.PositiveIntegerField(default=5)),
                ('price', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('health', models.PositiveIntegerField(default=50)),
                ('damage', models.PositiveIntegerField(default=5)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='game.map')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(default=0)),
                ('currency', models.PositiveIntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.ship')),
            ],
        ),
    ]
